services:
  my_money_vault_database:
    image: 'mysql:latest'
    container_name: my_money_vault_database
    environment:
      - MYSQL_ROOT_PASSWORD=myverystrongpassword
      - HOST_IP=host.docker.internal
    ports:
      - '3306:3306'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  my_money_vault_app:
    build:
      context: docker_configurations
      dockerfile: AppDockerfile
    volumes:
      - ./my_money_vault_app:/app
    ports:
      - 5000:5000
    working_dir: /app
    environment:
      - MYSQL_HOST=my_money_vault_database
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=myverystrongpassword
      - MYSQL_DATABASE=my_money_vault
      - MYSQL_HOST_TEST=my_money_vault_database
      - MYSQL_PORT_TEST=3306
      - MYSQL_USER_TEST=root
      - MYSQL_PASSWORD_TEST=myverystrongpassword
      - MYSQL_DATABASE_TEST=my_money_vault_test
